### ISSUE TITLE
What is the name of this programme?

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/techforbetter-website#44]
It could be, 

_**"TECH FOR GOOD PRODUCT DEVELOPMENT PROGRAMME"**_

which describes what it is, but is a bit of a mouthful. Or perhaps,

_**"SOCIAL IMPACT PRODUCT DEVELOPMENT PROGRAMME"**_

which works, too, although I am not very happy with that either.

Any better suggestions?

**Comment by MissArray** [comment]
'Code for the community' 
(perhaps?)

'Prosocial programming' 
(if you can stomach the first word?)

**Comment by arrested-developer** [comment]
“Developing Social Impact” ? 
“Programme for Developing Social Impact” ??
“Social Impact Development” ???
🤔

**Comment by thejoefriel** [comment]
I like the Developing Social Impact route as it plays on the web developer term. Could it be a smaller version of the original version, so drop product and have Social Impact Developers Programme?

**Comment by MissArray** [comment]
Maybe a *Title: Subtitle* format rather than a one-liner?

**Comment by sbinlondon** [comment]
@sofer you mentioned when you introduced the website to FAC-14 that you don't quite like the name 'tech for good', because it's not enough and who would make tech for bad?

I see where you're coming from and I think that is a good point. However to me, it's not that people *intend* to make tech for bad. Yet somehow so much tech exists that is bad in a way - think of Twitter's harassment problem, dark UI patterns on gambling apps, and mobile games that encourage addictive behaviour from users.

Some of these issues, like Twitter's harassment problem, weren't deliberately built into the platform. But through not being thoughtful about how that might come about, and not being thoughtful about it since it's become such a huge issue, their tech has become 'for bad' in some ways.

So how can we redefine 'tech for good' in a way that is more specific and captures how we feel about it? I think that to me, we want to be deliberate, conscientious, measured, purposeful, etc with what we build.

My idea is that we can turn "tech for good" => "tech for better". As in, yes you're doing good, but are you making the world a better place? It also plays off of 'tech for good', which is a known phrase, yet sets us apart. 

However, I'm aware that I'm sitting here looking at Outlandish's poster that says 'Technology for a fairer, better world' so perhaps this is too close, though I hope not.

Cons: people who like the 'tech for good' label might see this as us trying to 'one up' them by being 'better', though it's most certainly not suggested in that spirit 😅

**Comment by sbinlondon** [comment]
Riffing off of 'coding for the common good' strapline, maybe the headline can be "Tech for better: coding for the common good"?

**Comment by arrested-developer** [comment]
Suggested programme name:

**Founders And Coders Tech For Better:** A pro-bono programme using digital technology to create positive social impact.

Please comment with ideas / improvements / solutions!

**Comment by MissArray** [comment]
**Founders and Coders - Coding for the Community** 
**_Pro-bono programming for positive social impact_**

Rationale: 
* more specific titles are more self-explanatory than more general ones
* 'coding' (or similar) is the more specific instance of the broader concept of 'tech' that we're offering
* 'community' is the more specific instance of the broader concept of 'good' to which we're contributing

**Comment by sofer** [comment]
The name is, *"Tech for better"*.
